# Generated by Django 5.2.6 on 2025-12-11 19:24

from django.db import migrations

from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
