# Generated by Django 5.2.6 on 2026-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, max_length=250, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, max_length=250, null=True, unique=True, verbose_name='slug'),
        ),
    ]
