# Generated by Django 5.2.6 on 2026-01-21 21:02

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_category_image'),
        ('taggit', '0007_tag_name_ar_tag_name_en_tag_slug_ar_tag_slug_en'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_name_desc_gin',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_name_trgm',
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ar',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_ar'], name='prod_name_ar_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_ar'], name='prod_desc_ar_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_en'], name='prod_name_en_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_en'], name='prod_desc_en_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
