# Generated by Django 5.2.6 on 2026-03-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='base_price',
        ),
    ]
