# Generated by Django 5.2.6 on 2026-03-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_discount_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, max_length=250, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, max_length=250, null=True, unique=True, verbose_name='slug'),
        ),
    ]
