# Generated by Django 5.2.6 on 2026-03-07 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
            ],
            options={
                'verbose_name': 'product variant group',
                'verbose_name_plural': 'product variant groups',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_base_variant',
            field=models.BooleanField(default=False, verbose_name='base variant'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.productvariantgroup'),
        ),
    ]
