# Generated by Django 5.2.6 on 2026-03-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productvariantgroup_product_is_base_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_avaliable',
        ),
        migrations.AddField(
            model_name='product',
            name='variant_specifications',
            field=models.JSONField(default=dict, verbose_name='variant specifications'),
        ),
    ]
