# Generated by Django 5.2.6 on 2026-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_is_avaliable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_base_variant',
            field=models.BooleanField(default=True, verbose_name='base variant'),
        ),
    ]
