# Generated by Django 5.2.6 on 2026-03-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_is_base_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_specifications',
            field=models.JSONField(blank=True, null=True, verbose_name='variant specifications'),
        ),
    ]
