# Generated by Django 5.2.6 on 2026-03-08 08:41

from django.db import migrations


def update_is_base_variant(apps, schema_editor):
    """Update all existing Product records to set is_base_variant to True"""
    Product = apps.get_model('store', 'Product')
    Product.objects.all().update(is_base_variant=True)


def reverse_update(apps, schema_editor):
    """Reverse: set is_base_variant back to False"""
    Product = apps.get_model('store', 'Product')
    Product.objects.all().update(is_base_variant=False)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_variant_specifications'),
    ]

    operations = [
        migrations.RunPython(update_is_base_variant, reverse_update),
    ]
