# Generated by Django 5.2.6 on 2026-01-20 15:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'coupon', 'verbose_name_plural': 'coupons'},
        ),
        migrations.AlterModelOptions(
            name='couponusage',
            options={'verbose_name': 'coupon usage', 'verbose_name_plural': 'coupon usages'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.IntegerField(default=1, verbose_name='usage limit'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='valid from'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='valid to'),
        ),
        migrations.AlterField(
            model_name='couponusage',
            name='used_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='used at'),
        ),
    ]
