# Generated by Django 5.2.6 on 2026-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_options_alter_couponusage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.IntegerField(default=0, verbose_name='max discount'),
        ),
    ]
