# Generated by Django 5.2.6 on 2026-03-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_discount'),
        ('store', '0013_discount_alter_product_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
