"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

#  keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

#  don't run with debug turned on in production!
DEBUG = True

CART_SESSION_ID = 'cart'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "modeltranslation",

    "unfold",
    "unfold.contrib.filters", 
    "unfold.contrib.forms", 
    "unfold.contrib.inlines",

    "django_filters",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'taggit',

    'store.apps.StoreConfig',
    'cart.apps.CartConfig',
    'order.apps.OrderConfig',
    'payment.apps.PaymentConfig',
    'coupon.apps.CouponConfig',
    'authenticate.apps.AuthenticateConfig',
    
    'django.contrib.postgres',
    'social_django',
    'django_extensions',
    'debug_toolbar',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'cart.context_processors.cart', # Removed: Using AJAX instead
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# settings.py

# 1. Configure Redis as the Default Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", # Use DB 1 to separate from your raw Redis usage
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 2. Tell Sessions to use the Cache (Redis) instead of the Database
SESSION_ENGINE = "django.contrib.sessions.backends.cache"  
SESSION_CACHE_ALIAS = "default"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432')
    }
}


REDIS_HOST = config('REDIS_HOST')
REDIS_PORT = config('REDIS_PORT')
REDIS_DB = config('REDIS_DB')
# REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
# REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
# REDIS_DB = config('REDIS_DB', default=0, cast=int)



SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_OAUTH2_SECRET')

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')



STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')
STRIPE_API_VERSION = '2024-04-10'
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')




BOSTA_TOKEN = config('BOSTA_TOKEN')
BOSTA_BASE_URL = config('BOSTA_BASE_URL')
BOSTA_COUNTRY_ID = config('BOSTA_COUNTRY_ID')


PAYMOB_API_KEY= config('PAYMOB_API_KEY')
PAYMOB_SECRET_KEY= config('PAYMOB_SECRET_KEY')
PAYMOB_PUBLIC_KEY= config('PAYMOB_PUBLIC_KEY')
PAYMOB_BASE_URL= config('PAYMOB_BASE_URL')
PAYMOB_HMAC= config('PAYMOB_HMAC')
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'authenticate.authentication.EmailAuthBackend',
    'social_core.backends.google.GoogleOAuth2'
    ]
SOCIAL_AUTH_PIPELINE = [
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'authenticate.authentication.associate_by_email',  # Check for existing user by email
    'social_core.pipeline.user.create_user',  # Only creates if not found above
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
]




ALLOWED_HOSTS = ['mysite.com', 'localhost', '127.0.0.1', 'madonna-hypermoral-delbert.ngrok-free.dev']
INTERNAL_IPS = ['mysite.com', 'localhost', '127.0.0.1']

# Social Auth Redirects
LOGIN_URL = 'authenticate:login'
LOGIN_REDIRECT_URL = 'store:product_list_category'
LOGOUT_REDIRECT_URL = 'authenticate:login'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'store:product_list_category'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_FALLBACK_LANGUAGES = ('en', 'ar')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    # BASE_DIR.parent / 'static',  # project-level static at /.../new/static
    BASE_DIR / 'static', 
]
STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIGRATION_MODULES = {
    'taggit': 'store.migrations_taggit'
}
# settings.py
TAGGIT_STRIP_NON_ASCII_TAGS = False 
TAGGIT_CASE_INSENSITIVE = True

UNFOLD = {
    "SITE_TITLE": _("LuxeStore Admin"), # Use _() so it translates
    "SITE_HEADER": _("LuxeStore"),
    "SITE_SUBHEADER": _("Dashboard"),
    "SHOW_LANGUAGES": True,
    
    # Use a font that looks good in BOTH English and Arabic (e.g., Cairo or Tajawal)
    "STYLES": [
        "https://fonts.googleapis.com/css2?family=Cairo:wght@400;500;700&display=swap",
        "/static/css/admin_extra.css",
    ],
    "SHOW_VIEW_ON_SITE": True, # show/hide "View on site" button, default: True
    "SHOW_BACK_BUTTON": True, # show/hide "Back" button, default: True
    "SHOW_BREADCRUMBS": True, # show/hide breadcrumbs, default: True
    "SHOW_QUICK_SEARCH": True, # show/hide quick search, default: True
    "SHOW_HISTORY": True,
    # 3. Add a Search Box
    "COMMAND": {
        "search_models": ["store.Product", "order.Order"], #
    
    },

    # 4. Add a Language Switcher to the Sidebar
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Models"), # Translatable title
                "separator": True,
                "items": [
                    {
                        "title": _("Products"),
                        "link": reverse_lazy("admin:store_product_changelist"),
                    },
                    {
                        "title": _("Orders"),
                        "link": reverse_lazy("admin:order_order_changelist"),
                    },
                    {
                        "title": _("Product Variants group"),
                        "link": reverse_lazy("admin:store_productvariantgroup_changelist"),
                    },
                    {
                        "title": _("Categories"),
                        "link": reverse_lazy("admin:store_category_changelist"),
                    },
                    {
                        "title": _("Tags"),
                        "link": reverse_lazy("admin:taggit_tag_changelist"),
                    },
                    {
                        "title": _("Discounts"),
                        "link": reverse_lazy("admin:store_discount_changelist"),
                    },
                    {
                        "title": _("Coupons"),
                        "link": reverse_lazy("admin:coupon_coupon_changelist"),
                    },
                    {
                        "title": _("File Center"),
                        "link": reverse_lazy("admin:order_pdffile_changelist"),
                    },
                    {
                        "title": _("Users"),
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ]
            },
            {
                "title": _("Languages"), # Translatable title
                "separator": True,
                "items": [
                    {
                        "title": "English",
                        "icon": "language", 
                        "link": "/en/admin/", # Custom link (see Step 2)
                    },
                    {
                        "title": "العربية",
                        "icon": "language",
                        "link": "/ar/admin/", # Custom link (see Step 2)
                    },
                ],
            },
        ],
        
    },
}

