# Generated by Django 5.2.6 on 2026-01-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, max_length=100, null=True, unique=True, verbose_name='slug'),
        ),
    ]
