# Generated by Django 5.2.6 on 2026-01-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_coupon_order_discount_order_shipping_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='discount_amount',
        ),
    ]
