# Generated by Django 5.2.6 on 2026-01-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_options_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.BooleanField(default=False, verbose_name='shipping status'),
        ),
    ]
