# Generated by Django 5.2.6 on 2026-02-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='session ID'),
        ),
    ]
