# Generated by Django 5.2.6 on 2026-02-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='apartment'),
        ),
        migrations.AddField(
            model_name='order',
            name='buildingNumber',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='building number'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='floor'),
        ),
        migrations.AddField(
            model_name='order',
            name='secondLine',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='second line'),
        ),
    ]
