# Generated by Django 5.2.6 on 2026-02-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_apartment_order_buildingnumber_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='city ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='district_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='district ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='zone_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='zone ID'),
        ),
    ]
