# Generated by Django 5.2.6 on 2026-02-15 12:50

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_city_id_order_district_id_order_zone_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buildingNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='secondLine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zone_id',
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='EG', verbose_name='mobile')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=250, null=True, verbose_name='city')),
                ('city_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='city ID')),
                ('zone_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='zone ID')),
                ('district_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='district ID')),
                ('secondLine', models.CharField(blank=True, max_length=500, null=True, verbose_name='second line')),
                ('buildingNumber', models.CharField(blank=True, max_length=250, null=True, verbose_name='building number')),
                ('floor', models.CharField(blank=True, max_length=250, null=True, verbose_name='floor')),
                ('apartment', models.CharField(blank=True, max_length=250, null=True, verbose_name='apartment')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='order.order')),
            ],
        ),
    ]
