# Generated by Django 5.2.6 on 2026-02-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_address_remove_order_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='distinct',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='zone',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='zone'),
        ),
    ]
