# Generated by Django 5.2.6 on 2026-02-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderaddress_distinct_orderaddress_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='city_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='city ID'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='district_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='district ID'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='zone_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='zone ID'),
        ),
    ]
