# Generated by Django 5.2.6 on 2026-03-15 19:49

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_order_user_alter_orderitems_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='buildingNumber',
            field=models.CharField(default='00', max_length=250, verbose_name='building number'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='floor',
            field=models.CharField(default='00', max_length=250, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='01000000000', max_length=128, region='EG', verbose_name='mobile'),
        ),
    ]
