# Generated by Django 5.2.6 on 2026-03-15 19:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_orderaddress_buildingnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='buildingNumber',
            field=models.CharField(max_length=250, null=True, verbose_name='building number'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='floor',
            field=models.CharField(max_length=250, null=True, verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='EG', verbose_name='mobile'),
        ),
    ]
