# Generated by Django 5.2.6 on 2026-03-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_orderaddress_buildingnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='payment method'),
        ),
    ]
